spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to Prakash cards related prod APIs "
  contactDetails:
    name: "Prakash  Swaroop"
    email: "tiwariprakashprod965@gmail.com"
  onCallSupport:
    - 9113434145
    - 9113434146