services:
  accounts:
    image: "prakashvinayak2512/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prakash
  loans:
    image: "prakashvinayak2512/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prakash
  cards:
    image: "prakashvinayak2512/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prakash
networks:
  prakash:
    driver: "bridge"
