server:
  port: 8090


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: pranikloan
    password: pranikloan
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  profiles:
    active:
      - "qa"
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

build:
  version: "3.0"

loans:
  message: "Welcome to Prakash Loans related local APIs "
  contactDetails:
    name: "Prakash Swaroop Vinayak"
    email: "tiwariprakash965@gmail.com"
  onCallSupport:
    - 9113434141
    - 9113434142