spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"
loans:
  message: "Welcome to PrakashBank loans related production APIS"
  contactDetails:
    name: "Vinayak prod Lead"
    email: "tiwariprakashprod965@gmail.com"
  onCallSupport:
    - 9113434143
    - 9113434146