spring:
  config:
    activate:
      on-profile: "qa"



build:
  version: "2.0"

accounts:
  message: "Welcome to PrakashBank accounts related QA APIS"
  contactDetails:
    name: "Swaroop QA Lead"
    email: "tiwariprakashqa965@gmail.com"
  onCallSupport:
    - 9113434145
    - 9113434146