
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: pranik
    password: pranik
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

build:
  version: "1.0"

accounts:
  message: "Welcome to PrakashBank accounts related local APIS"
  contactDetails:
    name: "Prakash Swaroop Vinayak"
    email: "tiwariprakash965@gmail.com"
  onCallSupport:
    - 9113434141
    - 9113434142